parameters:
  projectPath: ''
  buildConfiguration: 'Release'
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: ${{ parameters.projectPath }}
    arguments: '-c ${{ parameters.buildConfiguration }} --no-restore /p:SkipGlobalToolInstall=true'
