# Build Solution Job
# Builds the entire solution once with all projects
# Publishes individual project artifacts in parallel after build completes
#
# Benefits:
# - Single NuGet restore for all shared packages
# - MSBuild intelligently builds projects in dependency order
# - Massive bandwidth savings (no redundant package downloads per project)
# - Faster build times (shared build cache)

parameters:
  services: []
  servicesCsvNormalized: ',,'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '10.0.x'
  includePreview: true
  solutionPath: 'Dhadgar.sln'

jobs:
- job: BuildSolution
  displayName: 'Build Solution'
  workspace:
    clean: all
  variables:
    BuildOutputDir: $(Build.SourcesDirectory)/artifacts/publish
  steps:
  - checkout: self

  - template: ../../Standalone/Steps/DotNet/UseDotNet.yml
    parameters:
      dotnetSdkVersion: ${{ parameters.dotnetSdkVersion }}
      includePreview: ${{ parameters.includePreview }}

  # Caching disabled - fresh restore/install is faster than cache download on hosted agents

  # Pre-install npm dependencies in parallel (runs all 5 npm ci commands concurrently)
  # This is faster than letting MSBuild run them sequentially during the build
  - bash: |
      set -e
      echo "Installing npm dependencies in parallel..."

      # Run all npm ci commands in parallel using background jobs
      (cd src/Dhadgar.BetterAuth && npm ci --prefer-offline --no-audit) &
      (cd src/Dhadgar.SharedAuth && npm ci --prefer-offline --no-audit) &
      (cd src/Dhadgar.Scope && npm ci --prefer-offline --no-audit) &
      (cd src/Dhadgar.ShoppingCart && npm ci --prefer-offline --no-audit) &
      (cd src/Dhadgar.Panel && npm ci --prefer-offline --no-audit) &

      # Wait for all background jobs to complete
      wait

      echo "All npm dependencies installed successfully"
    displayName: 'npm ci (parallel)'

  - template: ../../Standalone/Steps/DotNet/Restore.yml
    parameters:
      projectPath: ${{ parameters.solutionPath }}

  # Build entire solution with max parallelism
  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: ${{ parameters.solutionPath }}
      arguments: >
        -c ${{ parameters.buildConfiguration }}
        -m
        /p:SkipGlobalToolInstall=true

  # Publish and upload artifacts for each deployable project (interleaved for clarity)
  # Skip publishing artifacts in PRs - they're only needed for deployment stages
  - ${{ each svc in parameters.services }}:
    - ${{ if and(not(startsWith(svc.projectPath, 'tests/')), not(startsWith(svc.projectPath, 'src/Shared/')), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet pub: ${{ svc.id }}'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: ${{ svc.projectPath }}
          arguments: >
            -c ${{ parameters.buildConfiguration }}
            --no-build
            --no-restore
            -o "$(BuildOutputDir)/${{ replace(svc.id, '.', '_') }}"
            /p:SatelliteResourceLanguages=en-US
            /p:SkipGlobalToolInstall=true

      - task: PublishPipelineArtifact@1
        displayName: 'artifact: ${{ svc.id }}'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          targetPath: $(Build.SourcesDirectory)/artifacts/publish/${{ replace(svc.id, '.', '_') }}
          artifactName: src-${{ replace(svc.id, '.', '_') }}
          publishLocation: 'pipeline'
