parameters:
  service:
    id: ''
    projectPath: ''
    testProjectPath: ''
    deploy: ''
  buildConfiguration: 'Release'
  dotnetSdkVersion: '10.0.x'
  includePreview: true
  runTests: true
  collectCoverage: true
  publishArtifacts: true

jobs:
- job: Build_${{ replace(parameters.service.id, '.', '_') }}
  displayName: 'Build: ${{ parameters.service.id }}'
  variables:
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    TestResultsDir: $(Agent.TempDirectory)/testresults/${{ replace(parameters.service.id, '.', '_') }}
  steps:
  - checkout: self

  - template: ../../Standalone/Steps/DotNet/UseDotNet.yml
    parameters:
      dotnetSdkVersion: ${{ parameters.dotnetSdkVersion }}
      includePreview: ${{ parameters.includePreview }}

  - template: ../../Standalone/Steps/DotNet/CacheNuGet.yml
    parameters:
      keySuffix: ${{ parameters.service.projectPath }}

  - template: ../../Standalone/Steps/DotNet/Restore.yml
    parameters:
      projectPath: ${{ parameters.service.projectPath }}

  - template: ../../Standalone/Steps/DotNet/Build.yml
    parameters:
      projectPath: ${{ parameters.service.projectPath }}
      buildConfiguration: ${{ parameters.buildConfiguration }}

  - ${{ if eq(parameters.runTests, true) }}:
    - template: ../../Standalone/Steps/DotNet/TestAndCoverage.yml
      parameters:
        testProjectPath: ${{ parameters.service.testProjectPath }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        collectCoverage: ${{ parameters.collectCoverage }}
        resultsDirectory: $(TestResultsDir)

    - ${{ if eq(parameters.collectCoverage, true) }}:
      - template: ../../Standalone/Steps/DotNet/PublishCoverage.yml
        parameters:
          resultsDirectory: $(TestResultsDir)

  - pwsh: |
      $projectPath = '${{ parameters.service.projectPath }}'
      $projectDir = Split-Path $projectPath -Parent
      Write-Host "##vso[task.setvariable variable=ProjectDir]$projectDir"
      $publishDir = "$(Build.ArtifactStagingDirectory)/${{ replace(parameters.service.id, '.', '_') }}"
      Write-Host "##vso[task.setvariable variable=PublishDir]$publishDir"
    displayName: 'Resolve project directory'

  - pwsh: |
      if (Test-Path -LiteralPath "$(PublishDir)") {
        Remove-Item -LiteralPath "$(PublishDir)" -Recurse -Force
      }
      New-Item -ItemType Directory -Path "$(PublishDir)" -Force | Out-Null
    displayName: 'Clean publish directory'
    condition: and(succeeded(), eq('${{ parameters.publishArtifacts }}', 'true'))

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    condition: and(succeeded(), eq('${{ parameters.publishArtifacts }}', 'true'))
    inputs:
      command: 'publish'
      projects: ${{ parameters.service.projectPath }}
      arguments: >
        -c ${{ parameters.buildConfiguration }}
        -o "$(PublishDir)"
        /p:SatelliteResourceLanguages=en-US

  - task: PublishPipelineArtifact@1
    displayName: 'Publish release outputs'
    condition: and(succeeded(), eq('${{ parameters.publishArtifacts }}', 'true'))
    inputs:
      targetPath: '$(PublishDir)'
      artifactName: "src-${{ replace(parameters.service.id, '.', '_') }}"
      publishLocation: 'pipeline'
