# Deploy CLI Job
# Downloads CLI artifacts from Package stage and publishes to GitHub Releases
#
# This job expects artifacts from PackageCli job in Package stage

parameters:
  serviceName: ''
  environment: 'dev'
  projectPath: ''  # Not used for building anymore, kept for compatibility
  runtimes: 'win-x64;linux-x64;osx-x64'  # Not used for building anymore
  publishToGitHub: true
  isPreRelease: true

jobs:
  - deployment: DeployCli_${{ replace(parameters.serviceName, '.', '_') }}
    displayName: 'Deploy (CLI): ${{ parameters.serviceName }}'
    environment: 'meridian-${{ parameters.environment }}'
    pool:
      name: 'Sandbox Servers Agents'
    download: none
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none
            # Download CLI artifacts from Package stage
            - task: DownloadPipelineArtifact@2
              displayName: 'Download CLI artifacts'
              inputs:
                buildType: 'current'
                artifactName: cli-${{ replace(parameters.serviceName, '.', '_') }}
                targetPath: '$(Pipeline.Workspace)/cli-artifacts'

            # Create GitHub Release (if enabled and on main branch)
            - ${{ if eq(parameters.publishToGitHub, true) }}:
              - task: GitHubRelease@1
                displayName: 'Create GitHub Release'
                condition: succeeded()
                inputs:
                  gitHubConnection: 'github.com_SandboxServers'
                  repositoryName: '$(Build.Repository.Name)'
                  action: 'create'
                  target: '$(Build.SourceVersion)'
                  tagSource: 'userSpecifiedTag'
                  tag: 'cli-v$(Build.BuildNumber)'
                  title: 'CLI Release v$(Build.BuildNumber)'
                  isPreRelease: ${{ parameters.isPreRelease }}
                  releaseNotesSource: 'inline'
                  releaseNotesInline: |
                    ## CLI Release v$(Build.BuildNumber)

                    **Environment:** ${{ parameters.environment }}
                    **Build:** $(Build.BuildNumber)

                    ### Downloads
                    - Windows (x64): `${{ replace(parameters.serviceName, 'Dhadgar.', '') }}-win-x64.zip`
                    - Linux (x64): `${{ replace(parameters.serviceName, 'Dhadgar.', '') }}-linux-x64.tar.gz`
                    - macOS (x64): `${{ replace(parameters.serviceName, 'Dhadgar.', '') }}-osx-x64.tar.gz`
                  assets: '$(Pipeline.Workspace)/cli-artifacts/*'
                  addChangeLog: true
