parameters:
- name: services
  type: object
  default: []
- name: servicesCsvNormalized
  type: string
  default: ',,'
- name: buildConfiguration
  type: string
  default: 'Release'
- name: dotnetSdkVersion
  type: string
  default: '10.0.x'
- name: includePreview
  type: boolean
  default: true
- name: runTests
  type: boolean
  default: true
- name: collectCoverage
  type: boolean
  default: true
- name: testInSingleJob
  type: boolean
  default: false
- name: testTargetPath
  type: string
  default: ''
- name: deploy
  type: boolean
  default: true
- name: publishContainers
  type: boolean
  default: true
# Local dev compose deploys (agent demand selector for localdev stage)
- name: localAgentDemand
  type: string
  default: ''
# Helm publish/deploy settings
- name: publishHelmChart
  type: boolean
  default: true
- name: publishComposeAssets
  type: boolean
  default: true
- name: composeAssetPath
  type: string
  default: 'deploy/compose'
- name: composeAssetArtifactName
  type: string
  default: 'compose-assets'
- name: helmChartPath
  type: string
  default: 'deploy/kubernetes/helm/meridian-console'
- name: helmChartRoot
  type: string
  default: 'deploy/kubernetes/helm'
- name: helmChartName
  type: string
  default: 'meridian-console'
- name: helmVersion
  type: string
  default: '3.13.0'
- name: helmReleaseName
  type: string
  default: 'meridian'
- name: imageTag
  type: string
  default: '$(Build.BuildId)'
# Infrastructure provisioning parameters
- name: provisionInfrastructure
  type: boolean
  default: false
- name: provisionDns
  type: boolean
  default: false
- name: environmentsCsvNormalized
  type: string
  default: ',localdev,'
- name: azureServiceConnection
  type: string
  default: 'meridian-rg-sc-2'
- name: acrServiceConnection
  type: string
  default: 'meridianconsoleacr'
- name: acrLoginServer
  type: string
  default: 'meridianconsoleacr-etdvg4cthscffqdf.azurecr.io'
- name: acrName
  type: string
  default: 'meridianconsoleacr'
- name: cloudflareApiToken
  type: string
  default: ''
- name: tenantId
  type: string
  default: ''
- name: kubernetesServiceConnection
  type: string
  default: 'meridiank8s'
# Security scanning parameters
- name: runSecurityScans
  type: boolean
  default: true
- name: nvdApiKey
  type: string
  default: ''

stages:
# Build & Test Stage
- template: ../Stages/Build.yml
  parameters:
    services: ${{ parameters.services }}
    servicesCsvNormalized: ${{ parameters.servicesCsvNormalized }}
    buildConfiguration: ${{ parameters.buildConfiguration }}
    dotnetSdkVersion: ${{ parameters.dotnetSdkVersion }}
    includePreview: ${{ parameters.includePreview }}
    runTests: ${{ parameters.runTests }}
    collectCoverage: ${{ parameters.collectCoverage }}
    testInSingleJob: ${{ parameters.testInSingleJob }}
    testTargetPath: ${{ parameters.testTargetPath }}

# Package Stage (Container builds + binary packaging)
# Runs after Build, builds Docker images and packages CLI/Agent binaries
- template: ../Stages/Package.yml
  parameters:
    services: ${{ parameters.services }}
    servicesCsvNormalized: ${{ parameters.servicesCsvNormalized }}
    buildConfiguration: ${{ parameters.buildConfiguration }}
    publishContainers: ${{ parameters.publishContainers }}
    publishHelmChart: ${{ parameters.publishHelmChart }}
    publishComposeAssets: ${{ parameters.publishComposeAssets }}
    composeAssetPath: ${{ parameters.composeAssetPath }}
    composeAssetArtifactName: ${{ parameters.composeAssetArtifactName }}
    helmChartPath: ${{ parameters.helmChartPath }}
    helmChartRoot: ${{ parameters.helmChartRoot }}
    helmChartName: ${{ parameters.helmChartName }}
    helmVersion: ${{ parameters.helmVersion }}
    acrName: ${{ parameters.acrName }}
    acrServiceConnection: ${{ parameters.acrServiceConnection }}
    acrLoginServer: ${{ parameters.acrLoginServer }}
    azureServiceConnection: ${{ parameters.azureServiceConnection }}

# Security Scanning Stage
# Runs after Package, scans all container images + code for vulnerabilities
- ${{ if eq(parameters.runSecurityScans, true) }}:
  - template: ../../Standalone/Stages/Security.yml
    parameters:
      stageName: 'Security'
      displayName: 'Security Scanning'
      dependsOn: ['Package']
      pool:
        name: 'Sandbox Servers Agents'
      containerArtifacts:
        - name: container-Dhadgar_Billing
          imageName: dhadgar/billing
        - name: container-Dhadgar_Console
          imageName: dhadgar/console
        - name: container-Dhadgar_Discord
          imageName: dhadgar/discord
        - name: container-Dhadgar_Files
          imageName: dhadgar/files
        - name: container-Dhadgar_Firewall
          imageName: dhadgar/firewall
        - name: container-Dhadgar_Gateway
          imageName: dhadgar/gateway
        - name: container-Dhadgar_Identity
          imageName: dhadgar/identity
        - name: container-Dhadgar_Mods
          imageName: dhadgar/mods
        - name: container-Dhadgar_Nodes
          imageName: dhadgar/nodes
        - name: container-Dhadgar_Notifications
          imageName: dhadgar/notifications
        - name: container-Dhadgar_Secrets
          imageName: dhadgar/secrets
        - name: container-Dhadgar_Servers
          imageName: dhadgar/servers
        - name: container-Dhadgar_Tasks
          imageName: dhadgar/tasks
      runSast: true
      runSca: true
      scaTarget: 'Dhadgar.sln'
      runContainerScan: true
      runIacScan: true
      runSecretScan: true
      runSbom: true
      failOnCritical: true
      nvdApiKey: ${{ parameters.nvdApiKey }}

# Infrastructure Provisioning Stages (optional) - Loop through environments
- ${{ if eq(parameters.provisionInfrastructure, true) }}:
  # localdev
  - ${{ if contains(parameters.environmentsCsvNormalized, ',localdev,') }}:
    - template: ../Stages/Infrastructure.yml
      parameters:
        environment: localdev
        azureServiceConnection: ${{ parameters.azureServiceConnection }}
        cloudflareApiToken: ${{ parameters.cloudflareApiToken }}
        provisionAzure: ${{ parameters.provisionInfrastructure }}
        provisionDns: ${{ parameters.provisionDns }}
        tenantId: ${{ parameters.tenantId }}

  # dev
  - ${{ if contains(parameters.environmentsCsvNormalized, ',dev,') }}:
    - template: ../Stages/Infrastructure.yml
      parameters:
        environment: dev
        azureServiceConnection: ${{ parameters.azureServiceConnection }}
        cloudflareApiToken: ${{ parameters.cloudflareApiToken }}
        provisionAzure: ${{ parameters.provisionInfrastructure }}
        provisionDns: ${{ parameters.provisionDns }}
        tenantId: ${{ parameters.tenantId }}

  # staging
  - ${{ if contains(parameters.environmentsCsvNormalized, ',staging,') }}:
    - template: ../Stages/Infrastructure.yml
      parameters:
        environment: staging
        azureServiceConnection: ${{ parameters.azureServiceConnection }}
        cloudflareApiToken: ${{ parameters.cloudflareApiToken }}
        provisionAzure: ${{ parameters.provisionInfrastructure }}
        provisionDns: ${{ parameters.provisionDns }}
        tenantId: ${{ parameters.tenantId }}

  # prod
  - ${{ if contains(parameters.environmentsCsvNormalized, ',prod,') }}:
    - template: ../Stages/Infrastructure.yml
      parameters:
        environment: prod
        azureServiceConnection: ${{ parameters.azureServiceConnection }}
        cloudflareApiToken: ${{ parameters.cloudflareApiToken }}
        provisionAzure: ${{ parameters.provisionInfrastructure }}
        provisionDns: ${{ parameters.provisionDns }}
        tenantId: ${{ parameters.tenantId }}

# Deploy Stages (Compose, CLI, Agent, SWA deployments) - Loop through environments
# Downloads artifacts from Publish stage and deploys to target environments
- ${{ if eq(parameters.deploy, true) }}:
  # localdev
  - ${{ if contains(parameters.environmentsCsvNormalized, ',localdev,') }}:
    - template: ../Stages/Deploy.yml
      parameters:
        services: ${{ parameters.services }}
        servicesCsvNormalized: ${{ parameters.servicesCsvNormalized }}
        environment: localdev
        localAgentDemand: ${{ parameters.localAgentDemand }}
        acrServiceConnection: ${{ parameters.acrServiceConnection }}
        acrLoginServer: ${{ parameters.acrLoginServer }}
        acrName: ${{ parameters.acrName }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        deploy: ${{ parameters.deploy }}
        provisionInfrastructure: ${{ parameters.provisionInfrastructure }}
        kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
        azureServiceConnection: ${{ parameters.azureServiceConnection }}

  # dev
  - ${{ if contains(parameters.environmentsCsvNormalized, ',dev,') }}:
    - template: ../Stages/Deploy.yml
      parameters:
        services: ${{ parameters.services }}
        servicesCsvNormalized: ${{ parameters.servicesCsvNormalized }}
        environment: dev
        localAgentDemand: ${{ parameters.localAgentDemand }}
        acrServiceConnection: ${{ parameters.acrServiceConnection }}
        acrLoginServer: ${{ parameters.acrLoginServer }}
        acrName: ${{ parameters.acrName }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        deploy: ${{ parameters.deploy }}
        provisionInfrastructure: ${{ parameters.provisionInfrastructure }}
        kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
        azureServiceConnection: ${{ parameters.azureServiceConnection }}

  # staging
  - ${{ if contains(parameters.environmentsCsvNormalized, ',staging,') }}:
    - template: ../Stages/Deploy.yml
      parameters:
        services: ${{ parameters.services }}
        servicesCsvNormalized: ${{ parameters.servicesCsvNormalized }}
        environment: staging
        localAgentDemand: ${{ parameters.localAgentDemand }}
        acrServiceConnection: ${{ parameters.acrServiceConnection }}
        acrLoginServer: ${{ parameters.acrLoginServer }}
        acrName: ${{ parameters.acrName }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        deploy: ${{ parameters.deploy }}
        provisionInfrastructure: ${{ parameters.provisionInfrastructure }}
        kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
        azureServiceConnection: ${{ parameters.azureServiceConnection }}

  # prod
  - ${{ if contains(parameters.environmentsCsvNormalized, ',prod,') }}:
    - template: ../Stages/Deploy.yml
      parameters:
        services: ${{ parameters.services }}
        servicesCsvNormalized: ${{ parameters.servicesCsvNormalized }}
        environment: prod
        localAgentDemand: ${{ parameters.localAgentDemand }}
        acrServiceConnection: ${{ parameters.acrServiceConnection }}
        acrLoginServer: ${{ parameters.acrLoginServer }}
        acrName: ${{ parameters.acrName }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        deploy: ${{ parameters.deploy }}
        provisionInfrastructure: ${{ parameters.provisionInfrastructure }}
        kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
        azureServiceConnection: ${{ parameters.azureServiceConnection }}
