parameters:
  chartName: ''
  releaseName: ''
  namespace: ''
  valuesFile: ''
  chartVersion: ''
  helmRegistry: ''
  environment: ''
  deployTimeout: '10m'
  testTimeout: '5m'

jobs:
- deployment: deploy_helm
  displayName: 'Deploy ${{ parameters.environment }}'
  environment: '${{ parameters.environment }}'
  pool:
    vmImage: ubuntu-latest
  variables:
    - template: /pipeline/variables/${{ parameters.environment }}.yml@self
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../Steps/Helm/Deploy.yml@YAML
          parameters:
            chartName: ${{ parameters.chartName }}
            releaseName: ${{ parameters.releaseName }}
            namespace: ${{ parameters.namespace }}
            valuesFile: ${{ parameters.valuesFile }}
            chartVersion: ${{ parameters.chartVersion }}
            helmRegistry: ${{ parameters.helmRegistry }}
            upgrade: true
            timeout: ${{ parameters.deployTimeout }}
            testTimeout: ${{ parameters.testTimeout }}

        - task: Bash@3
          displayName: 'Check deployment status'
          condition: succeededOrFailed()
          inputs:
            targetType: 'inline'
            script: |
              helm status ${{ parameters.releaseName }} --namespace ${{ parameters.namespace }} --show-resources
