# Deploy Stage
# Deploys Meridian Console services to various targets
#
# Deployment types:
#   - compose: Docker Compose deployment to self-hosted environment (localdev only, uses images from Publish stage)
#   - helm: Helm/Kubernetes deployment (dev/staging/prod only, uses images from Publish stage)
#   - swa: Azure Static Web Apps deployment (Scope dev only, ShoppingCart all environments)
#   - cli: CLI binary distribution to GitHub Releases / storage (localdev only, uses artifacts from Package stage)
#   - agent: Agent binary distribution (localdev only, uses artifacts from Package stage)
#
# Dependencies:
#   - With infrastructure provisioning: Depends on Infrastructure_{environment} stage
#   - Without infrastructure provisioning: Depends on Publish stage
#
# Environment approvals:
#   - meridian-localdev: No approval required
#   - meridian-dev/staging/prod: Requires approval (configured in Azure DevOps UI)

parameters:
  services: []
  servicesCsvNormalized: ',,'
  environment: 'localdev'
  localAgentDemand: ''
  composeAssetArtifactName: 'compose-assets'
  composeAssetPath: 'compose'
  acrServiceConnection: 'meridianconsoleacr'
  acrLoginServer: 'meridianconsoleacr-etdvg4cthscffqdf.azurecr.io'
  acrName: 'meridianconsoleacr'
  deploy: true
  buildConfiguration: 'Release'
  provisionInfrastructure: false
  # Compose deployment settings
  composeProjectPath: 'deploy/compose'
  composeFile: 'docker-compose.services.acr.yml'
  infraComposeFile: 'docker-compose.dev.yml'
  # Kubernetes/Helm deployment settings
  kubernetesServiceConnection: ''
  azureServiceConnection: ''

stages:
  - stage: Deploy_${{ replace(parameters.environment, '-', '_') }}
    displayName: 'Deploy (${{ parameters.environment }})'
    ${{ if eq(parameters.provisionInfrastructure, true) }}:
      dependsOn: Infrastructure_${{ parameters.environment }}
    ${{ else }}:
      dependsOn: Package  # Changed from Publish (which is now disabled)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq('${{ parameters.deploy }}', 'true'))
    variables:
      Environment: ${{ parameters.environment }}
      BuildConfiguration: ${{ parameters.buildConfiguration }}
    jobs:
      # localdev ONLY: Docker Compose Stack Deployment
      - ${{ if eq(parameters.environment, 'localdev') }}:
        - template: ../Jobs/DeployComposeStack.yml
          parameters:
            environment: ${{ parameters.environment }}
            agentDemand: ${{ parameters.localAgentDemand }}
            composeAssetArtifactName: ${{ parameters.composeAssetArtifactName }}
            composeAssetPath: ${{ parameters.composeAssetPath }}
            acrServiceConnection: ${{ parameters.acrServiceConnection }}
            acrLoginServer: ${{ parameters.acrLoginServer }}
            composeProjectPath: ${{ parameters.composeProjectPath }}
            composeFile: ${{ parameters.composeFile }}
            infraComposeFile: ${{ parameters.infraComposeFile }}

      # localdev ONLY: CLI Distribution
      - ${{ if eq(parameters.environment, 'localdev') }}:
        - ${{ each svc in parameters.services }}:
          - ${{ if and(eq(svc.deploy, 'cli'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
            - template: ../Jobs/DeployCli.yml
              parameters:
                serviceName: ${{ svc.id }}
                environment: ${{ parameters.environment }}
                projectPath: ${{ svc.projectPath }}
                isPreRelease: ${{ ne(parameters.environment, 'prod') }}
                ${{ if svc.cli }}:
                  runtimes: ${{ coalesce(svc.cli.runtimes, 'win-x64;linux-x64;osx-x64') }}
                  publishToGitHub: ${{ coalesce(svc.cli.publishToGitHub, true) }}
                ${{ if not(svc.cli) }}:
                  publishToGitHub: true

      # localdev ONLY: Agent Distribution
      - ${{ if eq(parameters.environment, 'localdev') }}:
        - ${{ each svc in parameters.services }}:
          - ${{ if and(eq(svc.deploy, 'agent'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
            - template: ../Jobs/DeployAgent.yml
              parameters:
                serviceName: ${{ svc.id }}
                environment: ${{ parameters.environment }}
                projectPath: ${{ svc.projectPath }}
                isPreRelease: ${{ ne(parameters.environment, 'prod') }}
                ${{ if svc.agent }}:
                  runtimes: ${{ coalesce(svc.agent.runtimes, 'win-x64;linux-x64') }}
                  publishToGitHub: ${{ coalesce(svc.agent.publishToGitHub, true) }}
                ${{ if not(svc.agent) }}:
                  publishToGitHub: true

      # Static Web Apps - Scope (dev only)
      - job: DeployScope
        displayName: 'Deploy SWA: Scope'
        condition: eq('${{ parameters.environment }}', 'dev')
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
        - template: ../Steps/DeploySwa.yml
          parameters:
            apiToken: $(Dhadgar_Swa_ApiToken)
            appLocation: .
            outputLocation: _swa_publish/wwwroot
            appBuildCommand: dotnet publish src/Dhadgar.Scope/Dhadgar.Scope.csproj -c $(BuildConfiguration) -o _swa_publish

      # Static Web Apps - ShoppingCart (all environments)
      - job: DeployShoppingCart
        displayName: 'Deploy SWA: ShoppingCart'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
        - template: ../Steps/DeploySwa.yml
          parameters:
            apiToken: $(Dhadgar_ShoppingCart_Swa_ApiToken)
            appLocation: .
            outputLocation: _swa_publish/wwwroot
            appBuildCommand: dotnet publish src/Dhadgar.ShoppingCart/Dhadgar.ShoppingCart.csproj -c $(BuildConfiguration) -o _swa_publish

      # dev/staging/prod: Helm/Kubernetes Deployment
      - ${{ if ne(parameters.environment, 'localdev') }}:
        - deployment: DeployKubernetes
          displayName: 'Helm deploy to K8s'
          environment: 'meridian-${{ parameters.environment }}'
          pool:
            name: 'Sandbox Servers Agents'
          variables:
            Namespace: ${{ parameters.environment }}
            HelmChartVersion: $[ stageDependencies.Package.PackageHelm.outputs['helmPublish.HelmChartVersion'] ]
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: none
                  - download: none

                  - task: HelmInstaller@1
                    displayName: 'Install Helm'
                    inputs:
                      helmVersionToInstall: '3.13.0'

                  - task: Kubernetes@1
                    displayName: 'Login to Kubernetes'
                    inputs:
                      connectionType: 'Kubernetes Service Connection'
                      kubernetesServiceEndpoint: ${{ parameters.kubernetesServiceConnection }}
                      command: 'login'

                  - task: AzureCLI@2
                    displayName: 'Login to ACR for Helm OCI'
                    inputs:
                      azureSubscription: ${{ parameters.azureServiceConnection }}
                      scriptType: 'bash'
                      scriptLocation: 'inlineScript'
                      inlineScript: |
                        set -euo pipefail

                        ACR_NAME="${{ parameters.acrName }}"
                        ACR_LOGIN_SERVER="${{ parameters.acrLoginServer }}"

                        az acr login --name "$ACR_NAME"

                        ACCESS_TOKEN="$(az acr login --name "$ACR_NAME" --expose-token --output tsv --query accessToken)"
                        echo "$ACCESS_TOKEN" | helm registry login "$ACR_LOGIN_SERVER" \
                          --username 00000000-0000-0000-0000-000000000000 \
                          --password-stdin

                  - bash: |
                      set -euo pipefail

                      ACR_LOGIN_SERVER="${{ parameters.acrLoginServer }}"
                      CHART_NAME="meridian-console"
                      RELEASE_NAME="meridian"
                      NAMESPACE="$(Namespace)"
                      IMAGE_TAG="$(Build.BuildId)"
                      CHART_VERSION="$(HelmChartVersion)"

                      chart_ref="oci://${ACR_LOGIN_SERVER}/helm/${CHART_NAME}"
                      version_arg=""
                      if [ -n "$CHART_VERSION" ] && [ "$CHART_VERSION" != "null" ]; then
                        version_arg="--version $CHART_VERSION"
                      fi

                      echo "Deploying chart $chart_ref $version_arg to namespace $NAMESPACE"

                      helm upgrade --install "$RELEASE_NAME" "$chart_ref" \
                        --namespace "$NAMESPACE" \
                        --create-namespace \
                        $version_arg \
                        --set-string global.imageRegistry="$ACR_LOGIN_SERVER" \
                        --set-string gateway.image.tag="$IMAGE_TAG" \
                        --set-string identity.image.tag="$IMAGE_TAG" \
                        --set-string billing.image.tag="$IMAGE_TAG" \
                        --set-string servers.image.tag="$IMAGE_TAG" \
                        --set-string nodes.image.tag="$IMAGE_TAG" \
                        --set-string tasks.image.tag="$IMAGE_TAG" \
                        --set-string files.image.tag="$IMAGE_TAG" \
                        --set-string mods.image.tag="$IMAGE_TAG" \
                        --set-string console.image.tag="$IMAGE_TAG" \
                        --set-string notifications.image.tag="$IMAGE_TAG" \
                        --set-string firewall.image.tag="$IMAGE_TAG" \
                        --set-string secrets.image.tag="$IMAGE_TAG" \
                        --set-string discord.image.tag="$IMAGE_TAG"
                    displayName: 'Helm upgrade'

      # TODO: Panel website deployment (TBD - Astro? SWA? Azure App Service?)
      # - job: DeployPanel
      #   displayName: 'Deploy: Panel'
      #   pool:
      #     vmImage: 'ubuntu-latest'
      #   steps:
      #   - bash: echo "Panel deployment not yet implemented"
      #     displayName: 'Deploy Panel (TBD)'
