# Deploy Stage
# Deploys Meridian Console services to various targets
#
# Deployment types:
#   - compose: Docker Compose deployment to self-hosted environment (uses images from Publish stage)
#   - swa: Azure Static Web Apps deployment (Scope dev only, ShoppingCart all environments)
#   - cli: CLI binary distribution to GitHub Releases / storage (uses artifacts from Package stage)
#   - agent: Agent binary distribution (uses artifacts from Package stage)

parameters:
  services: []
  servicesCsvNormalized: ',,'
  environment: 'localdev'
  localAgentDemand: ''
  composeAssetArtifactName: 'compose-assets'
  composeAssetPath: 'compose'
  acrServiceConnection: 'meridianconsoleacr'
  acrLoginServer: 'meridianconsoleacr-etdvg4cthscffqdf.azurecr.io'
  deploy: true
  buildConfiguration: 'Release'
  # Compose deployment settings
  composeProjectPath: 'deploy/compose'
  composeFile: 'docker-compose.services.acr.yml'
  infraComposeFile: 'docker-compose.dev.yml'

stages:
  - stage: Deploy_${{ replace(parameters.environment, '-', '_') }}
    displayName: 'Deploy (${{ parameters.environment }})'
    dependsOn: Publish  # Depends on Publish stage for container images
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq('${{ parameters.deploy }}', 'true'))
    variables:
      Environment: ${{ parameters.environment }}
      BuildConfiguration: ${{ parameters.buildConfiguration }}
    jobs:
      # Docker Compose Stack Deployment (single job deploys entire stack)
      - template: ../Jobs/DeployComposeStack.yml
        parameters:
          environment: ${{ parameters.environment }}
          agentDemand: ${{ parameters.localAgentDemand }}
          composeAssetArtifactName: ${{ parameters.composeAssetArtifactName }}
          composeAssetPath: ${{ parameters.composeAssetPath }}
          acrServiceConnection: ${{ parameters.acrServiceConnection }}
          acrLoginServer: ${{ parameters.acrLoginServer }}
          composeProjectPath: ${{ parameters.composeProjectPath }}
          composeFile: ${{ parameters.composeFile }}
          infraComposeFile: ${{ parameters.infraComposeFile }}

      # CLI Distribution
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'cli'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/DeployCli.yml
            parameters:
              serviceName: ${{ svc.id }}
              environment: ${{ parameters.environment }}
              projectPath: ${{ svc.projectPath }}
              isPreRelease: ${{ ne(parameters.environment, 'prod') }}
              ${{ if svc.cli }}:
                runtimes: ${{ coalesce(svc.cli.runtimes, 'win-x64;linux-x64;osx-x64') }}
                publishToGitHub: ${{ coalesce(svc.cli.publishToGitHub, true) }}
              ${{ if not(svc.cli) }}:
                publishToGitHub: true

      # Agent Distribution
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'agent'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/DeployAgent.yml
            parameters:
              serviceName: ${{ svc.id }}
              environment: ${{ parameters.environment }}
              projectPath: ${{ svc.projectPath }}
              isPreRelease: ${{ ne(parameters.environment, 'prod') }}
              ${{ if svc.agent }}:
                runtimes: ${{ coalesce(svc.agent.runtimes, 'win-x64;linux-x64') }}
                publishToGitHub: ${{ coalesce(svc.agent.publishToGitHub, true) }}
              ${{ if not(svc.agent) }}:
                publishToGitHub: true

      # Static Web Apps - Scope (dev only)
      - job: DeployScope
        displayName: 'Deploy SWA: Scope'
        condition: eq('${{ parameters.environment }}', 'dev')
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
        - template: ../Steps/DeploySwa.yml
          parameters:
            apiToken: $(Dhadgar_Swa_ApiToken)
            appLocation: .
            outputLocation: _swa_publish/wwwroot
            appBuildCommand: dotnet publish src/Dhadgar.Scope/Dhadgar.Scope.csproj -c $(BuildConfiguration) -o _swa_publish

      # Static Web Apps - ShoppingCart (all environments)
      - job: DeployShoppingCart
        displayName: 'Deploy SWA: ShoppingCart'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
        - template: ../Steps/DeploySwa.yml
          parameters:
            apiToken: $(Dhadgar_ShoppingCart_Swa_ApiToken)
            appLocation: .
            outputLocation: _swa_publish/wwwroot
            appBuildCommand: dotnet publish src/Dhadgar.ShoppingCart/Dhadgar.ShoppingCart.csproj -c $(BuildConfiguration) -o _swa_publish

      # TODO: Panel website deployment (TBD - Astro? SWA? Azure App Service?)
      # - job: DeployPanel
      #   displayName: 'Deploy: Panel'
      #   pool:
      #     vmImage: 'ubuntu-latest'
      #   steps:
      #   - bash: echo "Panel deployment not yet implemented"
      #     displayName: 'Deploy Panel (TBD)'
