# Package Stage
# Builds Docker containers and packages binaries after successful Build stage
#
# This stage handles:
# - Building Docker images for 'compose' services (runs on all builds including PRs)
# - Packaging 'cli' binaries for multiple platforms (non-PR only)
# - Packaging 'agent' binaries with install scripts (non-PR only)
#
# Container images are saved as artifacts for the Publish stage

parameters:
  services: []
  servicesCsvNormalized: ',,'
  buildConfiguration: 'Release'
  acrServiceConnection: 'meridianconsoleacr'
  acrLoginServer: 'meridianconsoleacr-etdvg4cthscffqdf.azurecr.io'
  azureServiceConnection: ''
  publishContainers: true
  publishHelmChart: true
  helmChartPath: 'deploy/kubernetes/helm/meridian-console'
  helmChartRoot: 'deploy/kubernetes/helm'
  helmChartName: 'meridian-console'
  helmVersion: '3.13.0'
  acrName: 'meridianconsoleacr'
  publishComposeAssets: true
  composeAssetPath: 'deploy/compose'
  composeAssetArtifactName: 'compose-assets'

stages:
  - stage: Package
    displayName: 'Package & Containerize'
    dependsOn: Build
    condition: succeeded()
    jobs:
      # Build Docker images for compose services (runs on all builds including PRs)
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'compose'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/BuildContainer.yml
            parameters:
              service: ${{ svc }}
              acrServiceConnection: ${{ parameters.acrServiceConnection }}
              acrLoginServer: ${{ parameters.acrLoginServer }}

      # Package CLI binaries (non-PR only)
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'cli'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/PackageCli.yml
            parameters:
              service: ${{ svc }}
              buildConfiguration: ${{ parameters.buildConfiguration }}

      # Package Agent binaries (non-PR only)
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'agent'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/PackageAgent.yml
            parameters:
              service: ${{ svc }}
              buildConfiguration: ${{ parameters.buildConfiguration }}

      # Publish Helm chart to ACR (non-PR only)
      - ${{ if eq(parameters.publishHelmChart, true) }}:
        - template: ../Jobs/PackageHelm.yml
          parameters:
            chartPath: ${{ parameters.helmChartPath }}
            chartRoot: ${{ parameters.helmChartRoot }}
            chartName: ${{ parameters.helmChartName }}
            acrName: ${{ parameters.acrName }}
            acrLoginServer: ${{ parameters.acrLoginServer }}
            azureServiceConnection: ${{ parameters.azureServiceConnection }}
            helmVersion: ${{ parameters.helmVersion }}

      # Publish compose assets for localdev deploys (non-PR only)
      - ${{ if eq(parameters.publishComposeAssets, true) }}:
        - template: ../Jobs/PackageComposeAssets.yml
          parameters:
            composePath: ${{ parameters.composeAssetPath }}
            artifactName: ${{ parameters.composeAssetArtifactName }}

  # DISABLED: Publish stage - pushes container images to ACR (non-PR only, gated by publishContainers parameter)
  # Each microservice gets its own deployment job with environment for approval gates
  # Commented out because all compose services are disabled - services run locally on Docker Desktop
  # - stage: Publish
  #   displayName: 'Publish Containers'
  #   dependsOn: Package
  #   condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq('${{ parameters.publishContainers }}', 'true'))
  #   jobs:
  #     # Publish Docker images to ACR (one deployment job per microservice)
  #     - ${{ each svc in parameters.services }}:
  #       - ${{ if and(eq(svc.deploy, 'compose'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
  #         - template: ../Jobs/PublishContainer.yml
  #           parameters:
  #             service: ${{ svc }}
  #             acrServiceConnection: ${{ parameters.acrServiceConnection }}
  #             acrLoginServer: ${{ parameters.acrLoginServer }}
