# Package Stage
# Builds Docker containers and packages binaries after successful Build stage
#
# This stage handles:
# - Building Docker images for 'compose' services and pushing to ACR
# - Packaging 'cli' binaries for multiple platforms
# - Packaging 'agent' binaries with install scripts

parameters:
  services: []
  servicesCsvNormalized: ',,'
  buildConfiguration: 'Release'
  acrServiceConnection: 'meridianconsoleacr'
  acrLoginServer: 'meridianconsoleacr-etdvg4cthscffqdf.azurecr.io'
  publishHelmChart: true
  helmChartPath: 'deploy/kubernetes/helm/meridian-console'
  helmChartRoot: 'deploy/kubernetes/helm'
  helmChartName: 'meridian-console'
  helmVersion: '3.13.0'
  acrName: 'meridianconsoleacr'
  publishComposeAssets: true
  composeAssetPath: 'deploy/compose'
  composeAssetArtifactName: 'compose-assets'

stages:
  - stage: Package
    displayName: 'Package & Containerize'
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      # Placeholder job (ensures stage has at least one job)
      - job: Package_NoOp
        displayName: 'Package: no targets'
        condition: false
        steps:
          - script: echo "No package targets."

      # Build Docker images for compose services
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'compose'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/BuildContainer.yml
            parameters:
              service: ${{ svc }}
              acrServiceConnection: ${{ parameters.acrServiceConnection }}
              acrLoginServer: ${{ parameters.acrLoginServer }}

      # Package CLI binaries
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'cli'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/PackageCli.yml
            parameters:
              service: ${{ svc }}
              buildConfiguration: ${{ parameters.buildConfiguration }}

      # Package Agent binaries
      - ${{ each svc in parameters.services }}:
        - ${{ if and(eq(svc.deploy, 'agent'), or(eq(parameters.servicesCsvNormalized, ',,'), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(svc.id))), contains(lower(parameters.servicesCsvNormalized), format(',{0},', lower(replace(svc.id, 'Dhadgar.', '')))))) }}:
          - template: ../Jobs/PackageAgent.yml
            parameters:
              service: ${{ svc }}
              buildConfiguration: ${{ parameters.buildConfiguration }}

      # Publish Helm chart to ACR
      - ${{ if eq(parameters.publishHelmChart, true) }}:
        - template: ../Jobs/PackageHelm.yml
          parameters:
            chartPath: ${{ parameters.helmChartPath }}
            chartRoot: ${{ parameters.helmChartRoot }}
            chartName: ${{ parameters.helmChartName }}
            acrName: ${{ parameters.acrName }}
            acrLoginServer: ${{ parameters.acrLoginServer }}
            acrServiceConnection: ${{ parameters.acrServiceConnection }}
            helmVersion: ${{ parameters.helmVersion }}

      # Publish compose assets for localdev deploys
      - ${{ if eq(parameters.publishComposeAssets, true) }}:
        - template: ../Jobs/PackageComposeAssets.yml
          parameters:
            composePath: ${{ parameters.composeAssetPath }}
            artifactName: ${{ parameters.composeAssetArtifactName }}
