# Release Stage
# Deploys frontend applications (Static Web Apps) to Azure
#
# SWA deployments:
#   - Dhadgar.ShoppingCart: All environments (dev, staging, prod)
#   - Dhadgar.Scope: Dev only (documentation site)
#   - Dhadgar.Panel: TBD (future full-featured control plane UI)

parameters:
  services: []
  servicesCsvNormalized: ',,'
  buildConfiguration: 'Release'
  deploy: true
  environment: 'dev'

stages:
- stage: Release
  displayName: Release
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq('${{ parameters.deploy }}', 'true'))
  jobs:
  # Deploy all SWA sites in a single job
  - job: DeploySwaApps
    displayName: 'Deploy Static Web Apps'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      BuildConfiguration: ${{ parameters.buildConfiguration }}
    steps:
    - checkout: self

    # Deploy Scope (dev only)
    ${{ each svc in parameters.services }}:
      ${{ if and(eq(svc.deploy, 'swa'), eq(svc.id, 'Dhadgar.Scope'), eq(parameters.environment, 'dev')) }}:
        ${{ if svc.swa }}:
          - template: ../Steps/DeploySwa.yml
            parameters:
              apiToken: ${{ format('$({0})', svc.swa.apiTokenVar) }}
              appLocation: ${{ svc.swa.appLocation }}
              outputLocation: ${{ svc.swa.outputLocation }}
              appBuildCommand: ${{ svc.swa.appBuildCommand }}

    # Deploy ShoppingCart (all environments)
    ${{ each svc in parameters.services }}:
      ${{ if and(eq(svc.deploy, 'swa'), eq(svc.id, 'Dhadgar.ShoppingCart')) }}:
        ${{ if svc.swa }}:
          - template: ../Steps/DeploySwa.yml
            parameters:
              apiToken: ${{ format('$({0})', svc.swa.apiTokenVar) }}
              appLocation: ${{ svc.swa.appLocation }}
              outputLocation: ${{ svc.swa.outputLocation }}
              ${{ if svc.swa.apiLocation }}:
                apiLocation: ${{ svc.swa.apiLocation }}
              appBuildCommand: ${{ svc.swa.appBuildCommand }}

    # TODO: Panel website deployment (TBD - Astro? SWA? Azure App Service?)
    # - bash: echo "Panel deployment not yet implemented"
    #   displayName: 'Deploy Panel (TBD)'
