# Release Stage
# Deploys frontend applications (Static Web Apps) to Azure
#
# SWA deployments:
#   - Dhadgar.ShoppingCart: All environments (dev, staging, prod)
#   - Dhadgar.Scope: Dev only (documentation site)
#   - Dhadgar.Panel: TBD (future full-featured control plane UI)

parameters:
  services: []
  servicesCsvNormalized: ',,'
  buildConfiguration: 'Release'
  deploy: true
  environment: 'dev'

stages:
- stage: Release
  displayName: Release
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq('${{ parameters.deploy }}', 'true'))
  jobs:
  # Deploy Scope (dev only)
  - job: DeployScope
    displayName: 'Deploy SWA: Scope'
    condition: eq('${{ parameters.environment }}', 'dev')
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      BuildConfiguration: ${{ parameters.buildConfiguration }}
    steps:
    - checkout: self
    - template: ../Steps/DeploySwa.yml
      parameters:
        apiToken: $(Dhadgar_Swa_ApiToken)
        appLocation: .
        outputLocation: _swa_publish/wwwroot
        appBuildCommand: dotnet publish src/Dhadgar.Scope/Dhadgar.Scope.csproj -c $(BuildConfiguration) -o _swa_publish

  # Deploy ShoppingCart (all environments)
  - job: DeployShoppingCart
    displayName: 'Deploy SWA: ShoppingCart'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      BuildConfiguration: ${{ parameters.buildConfiguration }}
    steps:
    - checkout: self
    - template: ../Steps/DeploySwa.yml
      parameters:
        apiToken: $(Dhadgar_ShoppingCart_Swa_ApiToken)
        appLocation: .
        outputLocation: _swa_publish/wwwroot
        appBuildCommand: dotnet publish src/Dhadgar.ShoppingCart/Dhadgar.ShoppingCart.csproj -c $(BuildConfiguration) -o _swa_publish

  # TODO: Panel website deployment (TBD - Astro? SWA? Azure App Service?)
  # - job: DeployPanel
  #   displayName: 'Deploy: Panel'
  #   pool:
  #     vmImage: 'ubuntu-latest'
  #   steps:
  #   - bash: echo "Panel deployment not yet implemented"
  #     displayName: 'Deploy Panel (TBD)'
