variables:
  # Helm chart configuration
  helmChartName: meridian-console
  helmChartPath: deploy/kubernetes/helm/meridian-console
  helmVersion: 3.13.0

  # ACR configuration
  acrName: meridianconsoleacr

  # Build configuration
  buildReason: $(Build.Reason)
  sourceBranch: $(Build.SourceBranch)
