parameters:
- name: artifactName
  type: string
  default:
- name: environment
  type: string
  default:

jobs:
- deployment: deploy_${{ parameters.artifactName }}
  ${{ if eq(parameters['artifactName'], 'DB') }}:
    dependsOn:
    - deploy_infra
    pool:
      vmImage: windows-latest
  ${{ elseif eq(parameters['artifactName'], 'API') }}:
    dependsOn: 
    - deploy_infra
    - deploy_db
    pool:
      vmImage: windows-latest
  ${{ elseif eq(parameters['artifactName'], 'WWW') }}:
    dependsOn: 
    - deploy_infra
    - deploy_api
    pool:
      name: Sandbox Servers Linux Agents
  displayName: Deploy ${{ parameters.artifactName }}
  environment: "$(Build.DefinitionName)-${{ parameters.environment }}"
  variables:
    - template: /pipeline/variables/${{ parameters.environment }}.yml@self
  workspace:
    clean: all
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../../Standalone/Jobs/Bicep/Deploy.yml@YAML
          parameters:
            environment: ${{ parameters.environment }}
          #Used to perform a task that is not possible to do in bicep but must be run after bicep
          #When doing this, ensure the command you are using is capable of being run multiple times without throwing errors
          #Else, write the code so that it checks for a certain state and then runs the one-time code if it needs it.
          #If no action is required, do nothing.
        - task: AzureCLI@2
          displayName: Link domain to SWA
          inputs:
            azureSubscription: 'DriveBackup'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $env:AZURE_CORE_ONLY_SHOW_ERRORS = $true
              $env:AZURE_CORE_NO_COLOR = $true

              az staticwebapp hostname set --hostname testswa-$(environmentName).sandboxservers.games --name $(appName)-swa-$(environmentName) --no-wait
            addSpnToEnvironment: true
            workingDirectory: 'test'
            failOnStandardError: true
          #More post-bicep actions
          #Kinda surprised this isnt retrievable in bicep, but i couldnt find a way as of writing.
        - task: AzureCLI@2
          displayName: Save SWA API Key
          inputs:
            azureSubscription: 'DriveBackup'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $env:AZURE_CORE_ONLY_SHOW_ERRORS = $true
              $env:AZURE_CORE_NO_COLOR = $true

              $Key = (az staticwebapp secrets list --name $(appName)-swa-$(environmentName) | convertfrom-json).properties.apikey

              $KeyVaultName = (az pipelines variable-group list --group-name "$(Build.DefinitionName)-${{ parameters.environment }}" --org "https://dev.azure.com/sandboxservers" --project "stoneindustries" | convertfrom-json).providerdata.vault

              $Secret = az keyvault secret set --name SWA-DEPLOYMENT-TOKEN --vault-name $KeyVaultName --value $Key
            addSpnToEnvironment: true
            workingDirectory: 'test'
            failOnStandardError: true
          #This is settable in bicep but i decided to do it in Azure CLI For some reason.
        - task: AzureCLI@2
          displayName: Add SQL Admin
          inputs:
            azureSubscription: 'DriveBackup'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $env:AZURE_CORE_ONLY_SHOW_ERRORS = $true
              $env:AZURE_CORE_NO_COLOR = $true

              az sql server ad-admin create --display-name $(administratorLogin) --object-id $(administratorLoginId) --resource-group $(ResourceGroupName) --server $(appName)-sql
            addSpnToEnvironment: true
            workingDirectory: 'test'
            failOnStandardError: true
